apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-list-api
  labels:
    app: shopping-list-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-list-api
  template:
    metadata:
      labels:
        app: shopping-list-api
    spec:
      containers:
      - name: shopping-list-api
        image: raffaeleloi/shoppinglistapi:latest
        env:
        - name: MongoDB__ConnectionURI
          value: mongodb+srv://${SHOPPING_LIST_DB_USER}:${SHOPPING_LIST_DB_PASSWORD}@${RAFFA_LAB_DB_CLUSTER_ADDRESS}/?retryWrites=true&w=majority&appName=${RAFFA_LAB_DB_CLUSTER_NAME}
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m" 
        ports:
          - containerPort: 8080