name: CI-CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
    - main

permissions:
   id-token: write
   contents: read
   actions: read

env:
    SHOPPING_LIST_DB_USER: ${{ secrets.SHOPPING_LIST_DB_USER }}
    SHOPPING_LIST_DB_PASSWORD: ${{ secrets.SHOPPING_LIST_DB_PASSWORD }}
    RAFFA_LAB_DB_CLUSTER_ADDRESS: ${{ secrets.RAFFA_LAB_DB_CLUSTER_ADDRESS }}
    RAFFA_LAB_DB_CLUSTER_NAME: ${{ secrets.RAFFA_LAB_DB_CLUSTER_NAME }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

  # tests:
  #   name: Unit Tests
  #   runs-on: ubuntu-latest
  #   needs: build
   
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4

  #   - name: Domain Tests
  #     run: |
  #       cd tests
  #       cd ShoppingList.Domain.Tests    
  #       dotnet test 
        
  #   - name: Application Tests
  #     run: |
  #       cd tests
  #       cd ShoppingList.Application.Tetsts
  #       dotnet test 
        
  # integrationTests:
  #   name: Integration Tests
  #   runs-on: ubuntu-latest
  #   needs: tests

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4

  #   - name: App Settings Variable Substitution        
  #     run: |
  #       cd src
  #       cd ShoppingList.API

  #       sed -i 's|${SHOPPING_LIST_DB_USER}|'"$SHOPPING_LIST_DB_USER"'|g' appsettings.json
  #       sed -i 's|${SHOPPING_LIST_DB_PASSWORD}|'"$SHOPPING_LIST_DB_PASSWORD"'|g' appsettings.json
  #       sed -i 's|${RAFFA_LAB_DB_CLUSTER_ADDRESS}|'"$RAFFA_LAB_DB_CLUSTER_ADDRESS"'|g' appsettings.json
  #       sed -i 's|${RAFFA_LAB_DB_CLUSTER_NAME}|'"$RAFFA_LAB_DB_CLUSTER_NAME"'|g' appsettings.json
      
  #   - name: Behavior Tests
  #     run: |
  #       cd tests
  #       cd ShoppingList.Behavior.Tests
  #       dotnet test

  publishImage:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Get current datetime
      id: current-datetime
      env:
        CURRENT_DATETIME2: $(TZ=America/Sao_Paulo date +'%Y-%m-%dT%H:%M:%S%z')
      run: echo $CURRENT_DATETIME2

    - name: Build Docker Image
      id: build-image
      env:
        TAG_IMAGE: "${{ steps.build-image.outputs.time }}"
        DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/shopping-list-api:$current-datetime
      run: |
        echo $current-datetime 
        echo $TAG_IMAGE
        echo $DOCKER_IMAGE
        docker build -t $DOCKER_IMAGE .

    - name: Push Docker Image
      run: docker push $DOCKER_IMAGE
  
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: publishImage

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Replace variables in Kubernetes manifest
        run: |
          cd kubernetes
          
          sed -i 's|${${DOCKER_IMAGE}}|'"$${DOCKER_IMAGE}"'|g' deployment.yaml

          sed -i 's|${SHOPPING_LIST_DB_USER}|'"$SHOPPING_LIST_DB_USER"'|g' deployment.yaml
          sed -i 's|${SHOPPING_LIST_DB_PASSWORD}|'"$SHOPPING_LIST_DB_PASSWORD"'|g' deployment.yaml
          sed -i 's|${RAFFA_LAB_DB_CLUSTER_ADDRESS}|'"$RAFFA_LAB_DB_CLUSTER_ADDRESS"'|g' deployment.yaml
          sed -i 's|${RAFFA_LAB_DB_CLUSTER_NAME}|'"$RAFFA_LAB_DB_CLUSTER_NAME"'|g' deployment.yaml
      
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
          context: raffa-lab-cluster

      - name: Deploy to Kubernetes
        uses: Azure/k8s-deploy@v5
        with:
          namespace: 'shopping-list-api-ns'
          manifests: |
              kubernetes/deployment.yaml
              kubernetes/service.yaml